# Macos
- name: Install Brave Browser | macOS
  community.general.homebrew_cask:
    name: brave-browser
    state: present
  when: ansible_facts['os_family'] == 'Darwin'

# Debian
- block:
    - name: Ensure the /etc/apt/keyrings directory exists | Debian
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      become: true

    - name: Check if the Brave GPG key is already present | Debian
      stat:
        path: /etc/apt/keyrings/brave-browser-archive-keyring.gpg
      register: brave_gpg_key

    - name: Download Brave APT repository key if not present | Debian
      get_url:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        dest: /etc/apt/keyrings/brave-browser-archive-keyring.gpg
        mode: '0644'
      become: true
      when: not brave_gpg_key.stat.exists

    - name: Add Brave APT repository | Debian
      apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main
        state: present
        filename: brave-browser
      become: true

    - name: Install Brave Browser | Debian
      apt:
        name: brave-browser
        state: present
      become: true

    - name: Set Bookmarks | Debian
      when: (install_ssh_keys | default('no') | lower) in ['yes', 'y'] and ansible_os_family != "Windows"
      block:
        - name: Set Bookmarks | Debian
          file:
            path: '{{ ansible_env.HOME }}/.config/BraveSoftware/Brave-Browser/Default'
            state: directory
            mode: '0700'

        - name: Copy Encrypted Bookmarks | Debian
          copy:
            src: '{{ role_path }}/files/brave/Bookmarks.json'
            dest: '{{ ansible_env.HOME }}/.config/BraveSoftware/Brave-Browser/Default/Bookmarks'
            mode: '0600'
          changed_when: false
  when: ansible_facts['os_family'] == 'Debian' and type_of_system == 'desktop'

# RedHat
- block:
    - name: Ensure dnf-plugins-core is installed | RedHat
      dnf:
        name: dnf-plugins-core
        state: present

    - name: Add Brave DNF repository | RedHat
      ansible.builtin.dnf:
        name: brave-browser
        description: Brave Browser Repository
        baseurl: https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
        enabled: yes
        gpgcheck: yes

    - name: Install Brave Browser | RedHat
      dnf:
        name: brave-browser
        state: present
  when: ansible_facts['os_family'] == 'RedHat' and type_of_system == 'desktop'

- name: Set Brave as the default browser | Not macOS
  block:
    - name: Check current default browser | Not macOS
      command: xdg-settings get default-web-browser
      register: current_browser
      args:
        executable: /bin/zsh
      changed_when: false

    - name: Set default browser to Brave if not already set | Not macOS
      command: xdg-settings set default-web-browser brave-browser.desktop
      args:
        executable: /bin/zsh
      when: "'brave' not in current_browser.stdout | lower"
  when: ansible_facts['os_family'] in ['Debian', 'RedHat'] and type_of_system == 'desktop'

  # TODO: add bookmark bar and other settings
