- name: Define package list based on OS
  set_fact:
    packages: >-
      {%- if ansible_facts['os_family'] == 'Darwin' -%}
        ["python3", "rustup-init", "nvm"]
      {%- elif ansible_facts['os_family'] == 'Debian' -%}
        ["python3", "rustc"]
      {%- elif ansible_facts['os_family'] == 'RedHat' -%}
        ["python3", "rust"]
      {%- else -%}
        []
      {%- endif -%}

- name: Install Development Tools
  package:
    name: '{{ packages }}'
    state: present
  when: packages | length > 0

- block:
    - name: Install Node Version Manager
      become_user: '{{ ansible_user }}'
      shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      args:
        creates: '{{ ansible_env.HOME }}/.nvm/nvm.sh'

    - name: Install Node.js LTS
      shell: . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install --lts
      args:
        creates: '{{ ansible_env.HOME }}/.nvm/versions/node'
  when: ansible_facts['os_family'] in ['RedHat', 'Debian']

- name: Install npm global packages
  npm:
    name: '{{ item }}'
    global: yes
  loop:
    - pnpm
    - degit
    - nodemon
    - yarn
