- name: Define package list based on OS
  set_fact:
    packages: >-
      {%- if ansible_facts['os_family'] == 'Darwin' -%}
        ["python3", "rustup-init", "nvm"]
      {%- elif ansible_facts['os_family'] == 'Debian' -%}
        ["python3", "rustc"]
      {%- elif ansible_facts['os_family'] == 'RedHat' -%}
        ["python3", "rust"]
      {%- else -%}
        []
      {%- endif -%}

- name: Install Development Tools
  package:
    name: '{{ packages }}'
    state: present
  when: packages | length > 0

# Ubuntu & RedHat NVM
- block:
    - name: Install NVM
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      args:
        creates: '{{ ansible_env.HOME }}/.nvm/nvm.sh'

    - name: Ensure NVM is loaded in zsh
      lineinfile:
        path: '{{ ansible_env.HOME }}/.zshrc'
        line: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
        create: yes
        state: present

    - name: Verify NVM installation
      shell: >
        bash -c "source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm --version"
      register: nvm_version
      failed_when: nvm_version.rc != 0
      changed_when: false

    - name: Verify Node
      shell: >
        bash -c "source {{ ansible_env.HOME }}/.nvm/nvm.sh && node --version"
      register: node_version
      changed_when: false
      ignore_errors: true

    - name: Install Node.js LTS
      shell: >
        bash -c "source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install --lts"
      when: node_version.rc != 0

    - name: Use the LTS version of Node.js
      shell: >
        bash -c "source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm use --lts"
      when: node_version.rc != 0

    - name: Set default Node.js version
      shell: >
        bash -c "source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm alias default node"
  when: ansible_os_family in ['RedHat', 'Debian']

- name: Install npm global packages
  npm:
    name: '{{ item }}'
    global: yes
  loop:
    - pnpm
    - degit
    - nodemon
    - yarn
