- name: Define package list based on OS
  set_fact:
    packages: >-
      {%- if ansible_facts['os_family'] == 'Darwin' -%}
        ["python3", "rustup-init", "nvm"]
      {%- elif ansible_facts['os_family'] == 'Debian' -%}
        ["python3", "rustc"]
      {%- elif ansible_facts['os_family'] == 'RedHat' -%}
        ["python3", "rust"]
      {%- else -%}
        []
      {%- endif -%}

- name: Install Development Tools
  package:
    name: '{{ packages }}'
    state: present
  when: packages | length > 0

# Ubuntu & RedHat NVM
- block:
    - name: Install NVM
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      args:
        creates: '/root/.nvm/nvm.sh'

    - name: Verifiy NVM installation
      command: nvm --version
      register: nvm_version
      failed_when: nvm_version.rc != 0
      changed_when: false

    - name: Verifiy Node
      command: node --version
      register: node_version
      failed_when: node_version.rc != 0
      changed_when: false

    - name: Install Node.js LTS
      command: nvm install --lts
      when: node_version.rc == 0

    - name: Use the LTS version of Node.js
      command: nvm use --lts
      when: node_version.rc == 0
  when: ansible_os_family in ['RedHat', 'Debian']

- name: Install npm global packages
  npm:
    name: '{{ item }}'
    global: yes
  loop:
    - pnpm
    - degit
    - nodemon
    - yarn
