# macOS
- name: Installer Docker & Docker Compose | macOS
  homebrew:
    name:
      - docker
      - docker-compose
    state: present
  when: ansible_os_family == "Darwin"

# Debian
- block:
    - name: Add Docker's official GPG key | Debian
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker repository | Debian
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        filename: docker

    - name: Installer Docker & Docker Compose | Debian
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes
  when: ansible_os_family == "Debian"
  become: true

# RedHat
- block:
    - name: Remove existing Docker repository | RedHat
      ansible.builtin.dnf:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: absent
      when: ansible_os_family == "RedHat"

    - name: Install dnf-plugins-core
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present
      when: ansible_os_family == "RedHat"

    - name: Add Docker CE repository | RedHat
      ansible.builtin.yum_repository:
        name: docker-ce
        description: Docker CE Repository
        baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Installer Docker & Docker Compose | RedHat
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
  when: ansible_os_family == "RedHat"
  become: true

- name: Start Docker service | Not macOS
  service:
    name: docker
    state: started
    enabled: yes
  when: ansible_os_family != "Darwin"
  become: true
