# MacOS
- name: Install kubernetes | macOS
  when: ansible_os_family == 'Darwin'
  block:
    - name: Install kubectl | macOS
      homebrew:
        name: kubernetes-cli
        state: present
    - name: Install minikube | macOS
      homebrew:
        name: kind
        state: present
    - name: Install k9s | macOS
      homebrew:
        name: k9s
        state: present

# Debian
- name: Install Kubernetes | Debian
  when: ansible_os_family == 'Debian'
  block:
    - name: Ensure /etc/apt/keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Check if Kubernetes GPG key is already present
      stat:
        path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      register: kubernetes_gpg_key

    - name: Download Kubernetes GPG key if not present
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
        dest: /tmp/kubernetes-apt-keyring.gpg
        mode: '0644'
      when: not kubernetes_gpg_key.stat.exists

    - name: Convert Kubernetes GPG key to dearmored format
      command: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-apt-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      become: true
      when: not kubernetes_gpg_key.stat.exists

    - name: Set permissions for Kubernetes signing key
      file:
        path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        mode: '0644'
      when: not kubernetes_gpg_key.stat.exists

    - name: Add Kubernetes apt repository
      apt_repository:
        repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /'
        state: present
        filename: kubernetes
      become: true

    - name: Update apt package index
      apt:
        update_cache: yes
      changed_when: false
      become: true

    - name: Install kubectl
      apt:
        name: kubectl
        state: present
      become: true

    - name: Check if Minikube is already installed
      command: minikube version
      register: minikube_check
      ignore_errors: true
      changed_when: false

    - name: Download the latest Minikube Debian package
      get_url:
        url: 'https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb'
        dest: '/tmp/minikube_latest_amd64.deb'
        mode: '0644'
      when: minikube_check.rc != 0

    - name: Install Minikube package
      apt:
        deb: '/tmp/minikube_latest_amd64.deb'
        state: present
      become: true
      when: minikube_check.rc != 0

    - name: Verify Minikube installation
      command: minikube version
      register: minikube_version
      changed_when: false
# RedHat

