# MacOS
- name: Install kubernetes | macOS
  when: ansible_os_family == 'Darwin'
  block:
    - name: Install kubectl | macOS
      homebrew:
        name: kubernetes-cli
        state: present
    - name: Install minikube | macOS
      homebrew:
        name: kind
        state: present
    - name: Install k9s | macOS
      homebrew:
        name: k9s
        state: present

# Debian
- name: Install Kubernetes | Debian
  when: ansible_os_family == 'Debian'
  block:
    - name: Ensure /etc/apt/keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Check if Kubernetes GPG key is already present
      stat:
        path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      register: kubernetes_gpg_key

    - name: Download and install Kubernetes GPG key if not present
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        mode: '0644'
      when: not kubernetes_gpg_key.stat.exists

    - name: Add Kubernetes apt repository
      apt_repository:
        repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /'
        state: present
        filename: kubernetes

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install kubectl
      apt:
        name: kubectl
        state: present
# RedHat

