- block:
    - name: Install LaTeX on macOS
      homebrew:
        name: mactex
        state: present

    - name: Install LaTeX Workshop Extension in VS Code
      shell: code --install-extension James-Yu.latex-workshop
      args:
        executable: /bin/bash
      register: vscode_extensions
      changed_when: "'already installed' not in vscode_extensions.stdout"

  when: ansible_os_family == "Darwin"
