# macOS
- name: Installer mos | macOS
  community.general.homebrew_cask:
    name: mos
    state: present
  when: ansible_os_family == 'Darwin'

- name: remove warring flag
  shell:
    cmd: |
      xattr -r -d com.apple.quarantine /Applications/Mos.app
  when: ansible_os_family == 'Darwin'
