# macOS
- name: macOS settings
  when: ansible_os_family == "Darwin"
  block:
    - name: Apply user-level defaults
      block:
        - name: Require password immediately after screensaver starts
          community.general.osx_defaults:
            domain: com.apple.screensaver
            key: askForPassword
            type: int
            value: 1

        - name: Set screensaver password delay to zero
          community.general.osx_defaults:
            domain: com.apple.screensaver
            key: askForPasswordDelay
            type: int
            value: 0

        - name: Use List view by default in Finder
          community.general.osx_defaults:
            domain: com.apple.finder
            key: FXPreferredViewStyle
            type: string
            value: Nlsv

        - name: Show Path Bar in Finder
          community.general.osx_defaults:
            domain: com.apple.finder
            key: ShowPathBar
            type: bool
            value: true

        - name: Don't show hard drives on desktop
          community.general.osx_defaults:
            domain: com.apple.finder
            key: ShowHardDrivesOnDesktop
            type: bool
            value: false

        - name: Keep Terminal window open after shell exits
          community.general.osx_defaults:
            domain: com.apple.Terminal
            key: ShellExitAction
            type: int
            value: 1

        - name: Keep Terminal window open after shell exits
          community.general.osx_defaults:
            domain: com.apple.Terminal
            key: ShellExitAction
            type: int
            value: 1

        - name: Make screensaver never start on this Mac
          community.general.osx_defaults:
            domain: com.apple.screensaver
            host: "{{ ansible_facts['nodename'] }}"
            key: idleTime
            type: int
            value: 0
        - name: Show all filename extensions
          community.general.osx_defaults:
            domain: NSGlobalDomain
            key: AppleShowAllFiles
            type: bool
            value: true

        - name: Show Path Bar in Finder
          community.general.osx_defaults:
            domain: com.apple.finder
            key: ShowPathbar
            type: bool
            value: true

        - name: Finder set to List view
          community.general.osx_defaults:
            domain: com.apple.finder
            key: FXPreferredViewStyle
            type: string
            value: Nlsv

        - name: Focus Terminal
          community.general.osx_defaults:
            domain: com.apple.Terminal
            key: FocusFollowsMouse
            type: bool
            value: true

        - name: Empty Trash after 30 days
          community.general.osx_defaults:
            domain: com.apple.finder
            key: FXRemoveOldTrashItems
            type: bool
            value: true

        - name: remove warring about emptying trash
          community.general.osx_defaults:
            domain: com.apple.finder
            key: WarnOnEmptyTrash
            type: bool
            value: false

        - name: remove warring about rename files
          community.general.osx_defaults:
            domain: com.apple.finder
            key: FXEnableExtensionChangeWarning
            type: bool
            value: false

        - name: Dock on the left
          community.general.osx_defaults:
            domain: com.apple.dock
            key: orientation
            type: string
            value: left

        - name: Dock tile size
          community.general.osx_defaults:
            domain: com.apple.dock
            key: tilesize
            type: int
            value: 48

        - name: typing delay
          community.general.osx_defaults:
            domain: NSGlobalDomain
            key: InitialKeyRepeat
            type: int
            value: 15

        - name: typing speed
          community.general.osx_defaults:
            domain: NSGlobalDomain
            key: KeyRepeat
            type: int
            value: 2

        - name: Press hold to repeat
          community.general.osx_defaults:
            domain: NSGlobalDomain
            key: ApplePressAndHoldEnabled
            type: bool
            value: false

        - name: Remove click on wallpaper to see desktop
          community.general.osx_defaults:
            domain: com.apple.WindowManager
            key: EnableStandardClickToShowDesktop
            type: bool
            value: false

        - name: Show Wi-Fi in Control Center menu
          community.general.osx_defaults:
            domain: com.apple.controlcenter
            host: currentHost
            key: 'NSStatusItem Visible WiFi'
            type: int
            value: 1

        - name: Position Wi-Fi in Control Center menu
          community.general.osx_defaults:
            domain: com.apple.controlcenter
            host: currentHost
            key: 'NSStatusItem Preferred Position WiFi'
            type: int
            value: 9

        - name: Position WiFi in Control Center menu
          community.general.osx_defaults:
            domain: com.apple.controlcenter
            host: currentHost
            key: 'NSStatusItem Preferred Position WiFi'
            type: int
            value: 4

        - name: Show Bluetooth in Control Center menu
          community.general.osx_defaults:
            domain: com.apple.controlcenter
            host: currentHost
            key: 'NSStatusItem Visible Bluetooth'
            type: int
            value: 1

        - name: Position Bluetooth in Control Center menu
          community.general.osx_defaults:
            domain: com.apple.controlcenter
            host: currentHost
            key: 'NSStatusItem Preferred Position Bluetooth'
            type: int
            value: 5

        - name: Show Focus in Control Center menu
          community.general.osx_defaults:
            host: currentHost
            domain: com.apple.controlcenter
            key: 'NSStatusItem Visible FocusModes'
            type: int
            value: 1

        - name: Position Focus in Control Center menu
          community.general.osx_defaults:
            domain: com.apple.controlcenter
            host: currentHost
            key: 'NSStatusItem Preferred Position FocusModes'
            type: int
            value: 2

        - name: Show Sound in Control Center menu
          community.general.osx_defaults:
            domain: com.apple.controlcenter
            host: currentHost
            key: 'NSStatusItem Visible Sound'
            type: int
            value: 1

        - name: Position Sound in Control Center menu
          community.general.osx_defaults:
            domain: com.apple.controlcenter
            host: currentHost
            key: 'NSStatusItem Preferred Position Sound'
            type: int
            value: 3

        - name: Show Battery in Control Center menu
          community.general.osx_defaults:
            domain: com.apple.controlcenter
            host: currentHost
            key: 'NSStatusItem Visible Battery'
            type: int
            value: 1

        - name: Position Battery in Control Center menu
          community.general.osx_defaults:
            domain: com.apple.controlcenter
            host: currentHost
            key: 'NSStatusItem Preferred Position Battery'
            type: int
            value: 1

        - name: Hide AirDrop from Control Center menu
          community.general.osx_defaults:
            domain: com.apple.controlcenter
            host: currentHost
            key: 'NSStatusItem Visible AirDrop'
            type: int
            value: 0

        - name: Hide Spotlight from Control Center menu
          community.general.osx_defaults:
            domain: com.apple.controlcenter
            host: currentHost
            key: 'NSStatusItem Visible Spotlight'
            type: int
            value: 0

        - name: Hide Now Playing from Control Center menu
          community.general.osx_defaults:
            domain: com.apple.controlcenter
            host: currentHost
            key: 'NSStatusItem Visible NowPlaying'
            type: int
            value: 0

    - name: Apply system-level settings
      become: true
      become_user: root
      block:
        - name: Set display sleep to 1 minute on battery
          command: pmset -b displaysleep 1

        - name: Set display sleep to 2 minutes on AC power
          command: pmset -c displaysleep 2

        - name: Remove sound at the beginning
          shell: sudo nvram StartupMute=%01

    - name: Reset Finder
      command: killall Finder
      changed_when: false

    - name: Restart Dock
      command: killall Dock
      changed_when: false

    - name: Restart cfprefsd
      command: killall cfprefsd
      changed_when: false

    - name: Restart Control Center
      command: killall ControlCenter
      changed_when: false

    - name: Restart SystemUIServer
      command: killall SystemUIServer
      changed_when: false
# Mail need to do the following: sudo defaults write com.apple.mail ConversationViewSortDescending -bool true

# to config the safari
# Granting Full Disk Access to Terminal
# To resolve this, you need to grant Full Disk Access to the Terminal:

# Open System Settings.
# Navigate to Privacy & Security > Full Disk Access.
# Click the lock icon to make changes and enter your administrator password.
# Click the "+" button, then select and add Terminal from the Applications > Utilities folder.
# Ensure that Terminal is checked in the list.
# Restart Terminal to apply the changes.​
# GitHub
# +6
# Tenable®
# +6
# Wikipedia
# +6
