# macOS
- name: Apply user-level Finder/Terminal/screensaver defaults
  block:
    - name: Show hidden files in Finder on macOS
      community.general.osx_defaults:
        domain: com.apple.finder
        key: AppleShowAllFiles
        type: bool
        value: true

    - name: Require password immediately after screensaver starts
      community.general.osx_defaults:
        domain: com.apple.screensaver
        key: askForPassword
        type: int
        value: 1

    - name: Set screensaver password delay to zero
      community.general.osx_defaults:
        domain: com.apple.screensaver
        key: askForPasswordDelay
        type: int
        value: 0

    - name: Use List view by default in Finder
      community.general.osx_defaults:
        domain: com.apple.finder
        key: FXPreferredViewStyle
        type: string
        value: Nlsv
      register: _view_style

    - name: Show Path Bar in Finder
      community.general.osx_defaults:
        domain: com.apple.finder
        key: ShowPathBar
        type: bool
        value: true
      register: _path_bar

    - name: Don't show hard drives on desktop
      community.general.osx_defaults:
        domain: com.apple.finder
        key: ShowHardDrivesOnDesktop
        type: bool
        value: false
      register: _hide_drives
    - set_fact:
        finder_needs_restart: true
      when: _hide_drives.changed

    - name: Keep Terminal window open after shell exits
      community.general.osx_defaults:
        domain: com.apple.Terminal
        key: ShellExitAction
        type: int
        value: 1

    - name: Keep Terminal window open after shell exits
      community.general.osx_defaults:
        domain: com.apple.Terminal
        key: ShellExitAction
        type: int
        value: 1

    - name: Make screensaver never start on this Mac
      community.general.osx_defaults:
        domain: com.apple.screensaver
        host: "{{ ansible_facts['nodename'] }}"
        key: idleTime
        type: int
        value: 0

    - name: Restart Finder to apply changes
      command: killall Finder
      changed_when: false
  when: ansible_os_family == 'Darwin'

- name: Apply system-level settings
  block:
    - name: Set display sleep to 1 minute on battery
      command: pmset -b displaysleep 1

    - name: Set display sleep to 2 minutes on AC power
      command: pmset -c displaysleep 2

  when: ansible_os_family == 'Darwin'
  become: true
  become_user: root
