- block:
    - name: Install Java
      homebrew:
        name: java
        state: present

    - name: Install PlantUML via Homebrew
      homebrew:
        name: plantuml
        state: present

    - name: Get PlantUML install path
      command: brew --prefix plantuml
      register: plantuml_path
      changed_when: false

    - name: Install PlantUML Extension in VS Code
      shell: code --install-extension jebbs.plantuml
      args:
        executable: /bin/bash
      register: vscode_extensions
      changed_when: "'already installed' not in vscode_extensions.stdout"

  when: ansible_os_family == 'Darwin'
