# MacOS
- name: Install PlantUML | macOS
  when: ansible_os_family == "Darwin"
  block:
    - name: Install Java | macOS
      homebrew:
        name: java
        state: present

    - name: Install PlantUML via Homebrew | macOS
      homebrew:
        name: plantuml
        state: present

    - name: Get PlantUML install path | macOS
      command: brew --prefix plantuml
      register: plantuml_path
      args:
        executable: /bin/zsh
      changed_when: false

    - name: Ensure PlantUML JAR directory exists | macOS
      file:
        path: /usr/local/bin/
        state: directory
        mode: '0755'

# Debian
- name: Install Java & PlantUML | Ubuntu
  when: ansible_os_family == "Debian"
  block:
    - name: Install Java and dependencies | Debian
      apt:
        name:
          - default-jre
          - graphviz
        state: present
        update_cache: yes
      become: true

    - name: Ensure PlantUML directory exists | Ubuntu
      file:
        path: /opt/plantuml/
        state: directory
        mode: '0755'
      become: true

    - name: Download PlantUML JAR | Ubuntu
      get_url:
        url: 'https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar'
        dest: '/opt/plantuml/plantuml.jar'
        mode: '0755'
      become: true

# RedHat
- name: Install Java & PlantUML | RedHat
  when: ansible_os_family == "RedHat"
  block:
    - name: Install Java and dependencies | RedHat
      yum:
        name:
          - java-11-openjdk
          - graphviz
        state: present
      become: true

    - name: Ensure PlantUML directory exists | RedHat
      file:
        path: /opt/plantuml/
        state: directory
        mode: '0755'
      become: true

    - name: Download PlantUML JAR | RedHat
      get_url:
        url: 'https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar'
        dest: '/opt/plantuml/plantuml.jar'
        mode: '0755'
      become: true

- name: Ensure VS Code PlantUML extension is installed
  command: code --install-extension jebbs.plantuml
  args:
    executable: /bin/zsh
  register: vscode_extensions
  changed_when: "'already installed' not in vscode_extensions.stdout"

- name: Ensure PlantUML is in the PATH | Debian, RedHat
  when: ansible_os_family in ['Debian', 'RedHat']
  block:
    - name: Update PlantUML paths in VS Code settings.json | Debian, RedHat
      ansible.builtin.lineinfile:
        path: '{{ ansible_env.HOME }}/.config/Code/User/settings.json'
        regexp: '"markdown-preview-enhanced.plantumlJarPath":\s*".*/plantuml.jar"'
        line: '  "markdown-preview-enhanced.plantumlJarPath": "/opt/plantuml/plantuml.jar",'
        backrefs: yes
    # TODO: change the settings.json to make it idempotent
    - name: Update PlantUML jar path in VS Code settings.json | Debian, RedHat
      ansible.builtin.lineinfile:
        path: '{{ ansible_env.HOME }}/.config/Code/User/settings.json'
        regexp: '"plantuml.jar":\s*".*/plantuml.jar"'
        line: '  "plantuml.jar": "/opt/plantuml/plantuml.jar",'
        backrefs: yes
