- name: Setup macOS & Linux Environment
  hosts: localhost
  gather_facts: true

  vars_prompt:
    - name: install_ssh_keys
      prompt: 'Do you want to install SSH keys? (yes/y default: no)'
      private: no

  vars:
    install_ssh_keys: '{{ install_ssh_keys }}' # yes or no (default: no)
    type_of_system: 'desktop' # desktop or server

  roles:
    # - role: system
    # - role: common
    - role: software
