- name: Check if Homebrew is installed
  shell: command -v brew
  register: homebrew_check
  ignore_errors: true
  changed_when: false

- name: Install Homebrew (if missing)
  shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.zshrc
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
  args:
    creates: /home/linuxbrew/.linuxbrew/bin/brew
  when: ansible_os_family in ["Darwin", "Linux"] and homebrew_check.rc != 0

- name: Update Homebrew
  homebrew:
    update_homebrew: yes
  when: ansible_os_family in ["Darwin", "Linux"]

- name: Upgrade Homebrew Packages
  homebrew:
    upgrade_all: yes
  when: ansible_os_family in ["Darwin", "Linux"]

- name: Install Common Packages with Homebrew
  homebrew:
    name:
      - vim
      - git
      - zsh
      - curl
      - tmux
      - rustup-init
      - python
      - node
      - nvm
      - pnpm
      - yarn
      - wget
      - tree
      - htop
      - zsh-autosuggestions
      - k9s
      - nmap
    state: present
  when: ansible_os_family in ["Darwin", "Linux"]
