# MacOS
- name: Configure macOS system settings
  block:
    - name: Show all file extensions in Finder
      community.general.osx_defaults:
        domain: com.apple.finder
        key: AppleShowAllExtensions
        type: bool
        value: true

    - name: Require password immediately after screensaver starts
      community.general.osx_defaults:
        domain: com.apple.screensaver
        key: askForPassword
        type: int
        value: 1

    - name: Disable "Recent Apps" in Dock
      community.general.osx_defaults:
        domain: com.apple.dock
        key: show-recents
        type: bool
        value: false

    - name: Restart Finder and Dock
      command: killall Finder Dock
      changed_when: false
  when: ansible_os_family == "Darwin"

# Linux
- name: Configure Linux system settings
  block:
    - name: Check current screensaver lock setting
      shell: gsettings get org.gnome.desktop.screensaver lock-enabled
      register: screensaver_lock_status
      changed_when: false

    - name: Disable screensaver lock if enabled
      shell: gsettings set org.gnome.desktop.screensaver lock-enabled false
      when: screensaver_lock_status.stdout != 'false'

    - name: Check current GNOME animations setting
      shell: gsettings get org.gnome.desktop.interface enable-animations
      register: animations_status
      changed_when: false

    - name: Disable animations in GNOME if enabled
      shell: gsettings set org.gnome.desktop.interface enable-animations false
      when: animations_status.stdout != 'false'
  when: ansible_os_family != "Darwin"
