# Debian
- name: Set user profile picture | Debian
  when: ansible_facts['os_family'] == "Debian"
  block:
    - name: Copy profile picture to .face | Debian
      copy:
        src: '{{ role_path }}/files/profile_picture.png'
        dest: '{{ ansible_env.HOME }}/.face'
        mode: '0644'
        owner: '{{ ansible_user_id }}'
        group: '{{ ansible_user_id }}'
        become: true

# RedHat
- name: Set user profile picture | RedHat
  when: ansible_facts['os_family'] == "RedHat"
  become: true
  block:
    - name: Ensure AccountsService directories exist | RedHat
      file:
        path: '/var/lib/AccountsService/{{ item }}'
        state: directory
        mode: '0755'
        owner: 'root'
        group: 'root'
      loop:
        - icons
        - users
      become: true

    - name: Copy profile picture to AccountsService icons | RedHat
      copy:
        src: '{{ role_path }}/files/profile_picture.png'
        dest: '/var/lib/AccountsService/icons/{{ ansible_user_id }}'
        mode: '0644'
        owner: 'root'
        group: 'root'
      become: true

    - name: Check if AccountsService user file exists
      stat:
        path: '/var/lib/AccountsService/users/{{ ansible_user_id }}'
      register: accounts_service_file
      become: true

    - name: Create user configuration file for AccountsService | RedHat
      copy:
        dest: '/var/lib/AccountsService/users/{{ ansible_user_id }}'
        content: |
          [User]
          Icon=/var/lib/AccountsService/icons/{{ ansible_user_id }}
        mode: '0644'
        owner: 'root'
        group: 'root'
      become: true
      when: not accounts_service_file.stat.exists

    - name: Restart AccountsService daemon | RedHat
      systemd:
        name: accounts-daemon
        state: restarted
        enabled: yes
      become: true
