# Macos
- name: Install tmux and dependencies | macOS
  homebrew:
    name:
      - tmux
    state: present
  when: ansible_os_family == "Darwin"

# Debian
- name: Install tmux and dependencies | Debian
  apt:
    name:
      - tmux
      - xclip
    state: present
    update_cache: yes
  become: true
  when: ansible_os_family == "Debian"

# RedHat
- name: Install tmux and dependencies | RedHat
  yum:
    name:
      - tmux
      - xclip
    state: present
  become: true
  when: ansible_os_family == "RedHat"

- name: Clone TPM (Tmux Plugin Manager)
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: '{{ ansible_env.HOME }}/.tmux/plugins/tpm'
    update: yes

- name: Add configuration to tmux.conf
  blockinfile:
    path: '{{ ansible_env.HOME }}/.tmux.conf'
    marker: '# {mark} ANSIBLE MANAGED BLOCK: tmux.conf'
    block: |
      # General configuration added by Ansible
      {{ lookup('file', '{{ role_path }}/files/tmux/.tmux.conf') }}
    create: yes
    state: present

- name: Reload Tmux Configuration (if Tmux is running)
  shell: |
    tmux has-session 2>/dev/null && tmux source-file {{ ansible_env.HOME }}/.tmux.conf || true
  changed_when: false

- name: Install Tmux Plugins # TODO: make this idempotent
  shell: '{{ ansible_env.HOME }}/.tmux/plugins/tpm/bin/install_plugins'
  ignore_errors: true
  changed_when: false
