- name: Add configuration to vimrc
  blockinfile:
    path: '{{ ansible_env.HOME }}/.vimrc'
    marker: '# {mark} ANSIBLE MANAGED BLOCK: tmux.conf'
    block: |
      # General configuration added by Ansible
      {{ lookup('file', '{{ role_path }}/files/vim/.vimrc') }}
    create: yes
    state: present
